### PR TITLE
Updated src/imagenes/reducir.py to do faster image conversion using PIL

### PR DESCRIPTION
**Pull request by gurupratap-matharu**
### Image conversion using PIL

As suggested in the issue #40 , now we use **PIL** package in `src/imagenes/reducir.py` to do image conversion for us.

Earlier, image conversion was done by
 
1. Calling the external `convert` system call for each image
2. After resize the image was checked for errors
3. In case of no errors image was saved in the dist folder

This was slower and not efficient.

Now.

1. PIL library is installed and we call the Image class
2. Height and width parameters are identified for each image
3. Resizing is done internally based on the scaling percentage
4. New image is saved in the dist folder
5. In case image is not found we log the error.

The main conversion method looks like this

````
import Image

def scaleImage(frompath, topath, scale_factor):
    """
    Reduces the size ofan image by the scale_factor using the PIL library
    """
    scale_ratio = scale_factor / 100 # since scale_factor is in percentage
    try:
        im = Image.open(frompath)
    except IOError:
        logger.warning("Couldn't read image at %s" % frompath)
        return -1
    
    # pull out the original dimensions and calculate resized dimensions
    width, height = im.size 
    resize_tuple  = (width * scale_ratio, height * scale_ratio)
    
    # resize and save at new destination
    output_image = im.resize(resize_tuple)
    output_image.save(topath)
    logger.info("Success! Resized image saved at %s" % topath)
    
    return 0
````
Here we call the method to scale images..

````

def run(verbose):
    ...
    # scale image using PIL
    status = scaleImage(frompath=frompath, topath=topath, scale_factor=escl)
                
````

### CODE REVIEW

**Comment by facundobatista** [comment]
How do you know that calling the external process is slower than using Pillow?

Originally it was faster.

The whole point of issue #40 is exactly measuring what is faster. Let's settle that there and then we can come back to this PR.

**Comment by tenuki** [comment]
Esto asume PIL ya instalado en el sistema.. habria que modificar los requerimientos ademas de lo que dice facu.

**Comment by tenuki** [comment]
Este se puede cerrar porque #175 lo incluye..

**Comment by facundobatista** [comment]
#173 and #175 are badly mixed. 

First, #173 is about closing #40, when the point of #40 is to *measure*, not *change* stuff. 

Then #175 includes this, but also changes requirements.txt in a way that's challenged there.

I'd keep both open, until we decide a course of action (probably #175 would be the way to go, but it's unrelated to #40 there)

**Comment by tenuki** [comment]
Oh, ok! (and Sorry!)

**Comment by facundobatista** [comment]
we're heavily refactoring all this...

**Pull request closed without merging**
