### PR TITLE
Requirements.txt

### PR DESCRIPTION
**Pull request by gurupratap-matharu**
### Updated requirements.txt

In this branch we have

1. An updated requirements.txt file
2. This was created using the pip freeze command > requirements.txt
3. A Python2.7 virtual environment was created and the dependencies were installed only for this project
4. It was double checked that `utilities/cdpetron.py . /opt/somedir es --test-mode` works under this virtual environment
5. This will help other folks to get their virtual environment setup faster
6. To setup your own virtual environment you can do pip install -r requirements.txt
7. Just make sure that your virtual environment is Python2 and not python3

### CODE REVIEW

**Comment by facundobatista** [comment]
Hello Gurupratap!

Thanks for this work.

It would be GREAT to have CDPedia buildable inside a virtualenv and (mostly) not depend on external system packages.

Some changes that I'd request for this PR:

- Do not fill the requirements.txt with freeze result. Specify exactly what is needed (no their dependencies).

- Don't mix this PR with all the image reduction stuff.

Thanks!!!

**Comment by tenuki** [comment]
I would prefer to use a more updated version of pil ie: pillow for many reasons, mainly: forward compatibility and security.

In this chart you can find which versions are compatible with which python versions. I think py2 isn't yet deprecated in cdpedia so this can be useful: https://pillow.readthedocs.io/en/stable/installation.html#notes

**Comment by facundobatista** [comment]
#173 and #175 are badly mixed.

First, #173 is about closing #40, when the point of #40 is to measure, not change stuff.

Then #175 includes that one, but also changes requirements.txt in a way that's challenged here.

I'd keep both open, until we decide a course of action (probably #175 would be the way to go, but it's unrelated to #40).

**Comment by facundobatista** [comment]
We're crazy refactoring this. Thanks for your time!

**Pull request closed without merging**
